version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
      POSTGRES_DB: saasdb
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U sa']
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ../backend
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - '8080:8080'

  frontend:
    build: ../frontend
    ports:
      - '3000:80'
    depends_on:
      - backend

  jaeger:
    image: jaegertracing/all-in-one:1.55
    ports:
      - '16686:16686'

volumes:
  db_data: