server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: saas-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/saasdb}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:sa}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 4MB
  cache:
    type: ${SPRING_CACHE_TYPE:simple}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

security:
  jwt:
    secret: ${JWT_SECRET:change-me-in-prod}
    access-token-ttl-seconds: ${JWT_ACCESS_TTL:900}
    refresh-token-ttl-seconds: ${JWT_REFRESH_TTL:1209600}
  rate-limit:
    enabled: ${RATE_LIMIT_ENABLED:true}
    requests-per-minute: ${RATE_LIMIT_RPM:120}

logging:
  level:
    root: INFO
    org.springframework.security: INFO

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:55432/saasdb_test
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false