---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:saasdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  flyway:
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
logging:
  level:
    root: INFO